###
#   Execute a command other than install and create_superuser
#
---
- name: Create command create_superuser
  command:
    "{{ service_script }} create_superuser --username {{ su_login }} --email {{ su_email }} --password {{ su_password }}"
  when: command == "create_superuser"

- name: Execute command {{ command }}
  command:
    "{{ service_script }} {{ command }}"
  when: command != "create_superuser"
