---
- name: Check if service path {{ service_running_path }} is available
  stat: path="{{ service_running_path }}"
  register: check_service_running_path

- name: Get the name of current latest version
  shell: "readlink -f {{ service_latest_path }}"
  register: service_latest_path_version

- name: Get the name of current running version
  shell: "readlink -f {{ service_running_path }}"
  when: check_service_running_path.stat.exists
  register: service_running_path_version

- name: Symlink to ROLLBACK path {{ service_rollback_path }}
  file:
    src="{{ service_running_path_version.stdout }}"
    path="{{ service_rollback_path }}"
    state=link
  when: check_service_running_path.stat.exists

- name: Stop servers
  command:
    "{{ service_script }} {{ item }} stop"
  with_items: "{{ lux_services }}"
  when: check_service_running_path.stat.exists

- name: Symlink to RUNNING path {{ service_latest_path_version.stdout }} to {{ service_running_path }}
  file:
    src="{{ service_latest_path_version.stdout }}"
    path="{{ service_running_path }}"
    state=link

- name: Start servers with {{ service_script }}
  command:
    "{{ service_script }} {{ item }} serve"
  with_items: "{{ lux_services }}"
