- include: install_start.yml

- include: install_repo.yml
  become: yes
  become_user: "{{ service_user }}"

- include: install_content.yml
  when: github_content_repository != ""
  become: yes
  become_user: "{{ service_user }}"

- include: install_finish.yml
  become: yes
  become_user: "{{ service_user }}"
