- include: install.yml
  when: command == "install"

- name: Check if service path {{ service_latest_path }} is available
  stat: path="{{ service_latest_path }}"
  register: latest_path

- include: command.yml
  when: command != 'install' and latest_path.stat.exists
  become: yes
  become_user: "{{ service_user }}"
