- include: install.yml
  when: command == "install"

- name: Check if service path {{ service_home_path }}/latest is available
  stat: path={{ service_home_path }}/latest
  register: latest_path

- include: command.yml
  when: command != 'install' and latest_path.stat.exists
  become: yes
  become_user: "{{ service_user }}"
