---
ssl_passphrase: changeme
nginx_state: install
nginx_conf_dir: /etc/nginx
server_crt_dir: /etc/ssl
acme_challenge_path: false
acme_challenge_location: /.well-known/acme-challenge/
nginx_resolver: 8.8.8.8

nginx_default_index_html: |
  <html>
    <head>
      <title>Your site</title>
    </head>
    <body>
      <h1></h1>
    </body>
  </html>

#
# if specified, download certificates from this s3 bucket
certificate_bucket: ""

