language: python

python:
  - 3.5.2

install:
  - pip install -r requirements-dev.txt

script:
  - flake8
  - python setup.py test --coverage -q --log-level error
  - python setup.py test --coveralls

notifications:
  email: false
