language: python

python:
  - 3.5.1

install:
  - pip install -r requirements-dev.txt

script:
  - flake8
  - python setup.py test --coverage -q --log-level error
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5.1 ]]; then python setup.py test --coveralls; fi

notifications:
  email: false

branches:
  only:
    - master
