language: python

python:
  - 3.5.1

install:
  - pip install -r requirements-dev.txt
  - pip install -r requirements.txt

script:
  - flake8
  - python -m runtests --coverage --log-level info
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5.1 ]]; then python -m runtests --coveralls; fi

notifications:
  email: false

branches:
  only:
    - master
    - py35
