language: python

python:
  - 3.4.3
  - 3.5.1

script:
  - flake8
  - python -m runtests --coverage --log-level info
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5.1 ]]; then python -m runtests --coveralls; fi

notifications:
  email: false

branches:
  only:
    - master
