language: python

python:
  - 3.5.2
  - 3.6-dev

install:
  - pip install -U -r requirements-dev.txt

script:
  - flake8
  - python setup.py test --coverage -q --log-level error

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.5.2' ]]; then python setup.py test --coveralls; fi

notifications:
  email: false
