---
- name: Create the Dockerfile in {{ openresty_volume_path }}
  template:
    src=Dockerfile.j2
    dest="{{ openresty_volume_path }}/Dockerfile"

- name: copy nginx.conf template to {{ openresty_volume_path }}/nginx.conf
  template:
    src=nginx.conf.j2
    dest="{{ openresty_volume_path }}/nginx.conf"

- name: create a new {{ image_name }} and push to {{ docker_repo }}
  docker_image:
    path="{{ openresty_volume_path }}"
    name="{{ docker_repo }}/{{ image_name }}"
    tag="{{ tag }}"
    force=true
    push=true
