
- name: Make sure "{{ ssh_config_path }}" is available and owned by the "{{ ssh_config_user }}"
  file:
    path="{{ ssh_config_path }}"
    owner={{ ssh_config_user }}
    state=directory

- name: Remove the "{{ ssh_config_path }}/conf.d" directory
  file:
    dest="{{ ssh_config_path }}/conf.d"
    state=absent

- name: Create the "{{ ssh_config_path }}/conf.d" directory
  file:
    dest="{{ ssh_config_path }}/conf.d"
    state=directory

- name: Fetch deployment keys
  include: deployment-key.yml
  with_items: "{{ deploy_keys }}"

- name: Create the "{{ ssh_config_path }}/config" file
  assemble:
    src="{{ ssh_config_path }}/conf.d"
    dest="{{ ssh_config_path }}/config"
    owner="{{ ssh_config_user }}"

- name: Remove the "{{ ssh_config_path }}/conf.d" directory
  file:
    dest="{{ ssh_config_path }}/conf.d"
    state=absent
