from . import vars      # noqa
from . import docs      # noqa
from . import httpcopy  # noqa
from . import labels    # noqa
from . import github    # noqa
from . import sass      # noqa
from . import shell     # noqa
from . import s3        # noqa
from . import watch     # noqa
from . import python    # noqa
from . import template  # noqa
from . import tasks     # noqa
