# ##############################################
# DEPLOYMENT KEYS
# List of deployment keys and their location
deploy_keys: []
# location of deployment keys and ssh config file
ssh_config_path: "{{ ansible_env.HOME }}/.ssh"
ssh_config_user: "{{ ansible_env.USER }}"
#
# directory when the id_rsa keys are placed in the target location
ssh_config_path_target: "{{ ssh_config_path }}"
