- name: ensure aptitude is installed
  apt: pkg=aptitude state=present
  become: yes

- name: update apt {{ ansible_env.USER }}
  apt: update_cache=yes upgrade=full cache_valid_time=86400 force=yes
  become: yes

- name: install python dependency packages
  apt: pkg={{item}} state=present force=yes
  with_items:
    - git
    - curl
    - libssl-dev
    - libbz2-dev
    - libsqlite3-dev
    - libreadline-dev
    - pkgconf
    - libhdf5-8
    - libhdf5-dev
    - liblzo2-dev
    - libpq-dev
    - build-essential
    - python-pip
    - python3
    - python3-dev
    - python3-pip
  become: yes

- name: install numpy dependency packages
  apt: pkg={{item}} state=present force=yes
  when: numpy == "yes"
  with_items:
    - gfortran
    - libblas-dev
    - liblapack-dev
  become: yes
