###
#   Make sure directories are available
#
---
- name: Make sure certificate directories are available
  file:
    path="{{ server_crt_dir }}/{{ item.domain }}"
    state=directory
  with_items: "{{ services }}"
  when: item.certificate is defined and item.domain is defined
