###
#   Make sure directories are available
#
---
- name: Make sure certificate directories are available
  file:
    path="{{ server_crt_dir }}/{{ item.filename | default(item.domain) }}"
    state=directory
  with_items: "{{ services }}"
  when: item.certificate is defined and item.domain is defined

- name: make sure {{ nginx_conf_dir }}/conf.d is available
  file:
    path="{{ nginx_conf_dir }}/conf.d"
    state=directory

- name: make sure {{ nginx_conf_dir }}/sites-available is available
  file:
    path="{{ nginx_conf_dir }}/sites-available"
    state=directory

- name: make sure {{ nginx_conf_dir }}/sites-enabled is available
  file:
    path="{{ nginx_conf_dir }}/sites-enabled"
    state=directory
