###
#   Install nginx configuration files for services providing the <domain> key
#
---
- name: copy server conf files to {{ nginx_conf_dir }}/sites-available
  template:
    src="nginx.conf.j2"
    dest="{{ nginx_conf_dir }}/sites-available/{{ item.domain }}.conf"
  with_items: "{{ services }}"
  when: item.domain is defined

- name: create symlinks in {{ nginx_conf_dir }}/sites-enabled
  file:
    src="{{ nginx_conf_dir }}/sites-available/{{ item.domain }}.conf"
    path="{{ nginx_conf_dir }}/sites-enabled/{{ item.domain }}.conf"
    state=link
  with_items: "{{ services }}"
  when: item.domain is defined

