###
#   Install nginx configuration files for services providing the <domain> key
#
---
- name: copy nginx.conf file to {{ nginx_conf_dir }}/nginx.conf
  template:
    src="nginx.conf.j2"
    dest="{{ nginx_conf_dir }}/nginx.conf"

- name: copy server conf files to {{ nginx_conf_dir }}/sites-available
  template:
    src="server.conf.j2"
    dest="{{ nginx_conf_dir }}/sites-available/{{ item.filename | default(item.domain) }}.conf"
  with_items: "{{ services }}"
  when: item.domain is defined

- name: create symlinks in {{ nginx_conf_dir }}/sites-enabled
  file:
    src="{{ nginx_conf_dir }}/sites-available/{{ item.filename | default(item.domain) }}.conf"
    path="{{ nginx_conf_dir }}/sites-enabled/{{ item.filename | default(item.domain) }}.conf"
    state=link
  with_items: "{{ services }}"
  when: item.domain is defined

- name: copy additional configuration files into {{ nginx_conf_dir }}/conf.d
  template:
    src="{{ item }}"
    dest="{{ nginx_conf_dir }}/conf.d/{{ item }}"
  with_items: "{{ nginx_config_templates }}"
