---
- include: install.yml
  become: yes
  when: postgresql_command == 'install'

- include: create.yml
  when: postgresql_command == 'create'

- include: drop.yml
  when: postgresql_command == 'drop'

- include: dump.yml
  when: postgresql_command == 'dump'

- include: restore.yml
  when: postgresql_command == 'restore'
